---
title: "Election Data by State for the 2016 Presidential Elections"
output: pdf_document
date: '2020-03-13'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
```
Madison Brenner
mb57363


The following data sets are titled 'Election16' 'RaceData16' and were pulled from https://vincentarelbundock.github.io/Rdatasets/datasets.html and the U.S. Census website. These two datasets together compile statistics on the demographics of voters by state in the 2016 presidential election. Election16 datasets contain the fifty states, the abbreviation for each state, the per capita income by state, the percent of high school graduates, percent of college graduates, percent of individuals with advanced degrees, the difference between republican and democrat percentages by state, and finally the winner of the election. RaceData16 contains the state, and then breaks down the overall population of the state by race. These specific variables were compiled into these datasets based on information from U.S. Census data, U.S. Census estimates, and Gallup polls. I personally find political data very interesting, and think that this past presidential elections was one of the most important and historical victories to date. While this does not explicitly take into account the percent of registered voters by race, I still expect to find some correlation between minority percentages in states and Democratic versus Republican percentages, and I also think that there will be interesting differences between states that are primarily one party but may have voted overall against their party. Finally, I expect that there will be obvious correlations between education levels and party affiliation between states. 

```{R}
library(tidyverse)
library(dplyr)
election16 <- read.csv("~/Downloads/election16.csv")
race_data_2016 <- read.csv("~/Downloads/race.data.2016.csv")
election16 <- election16%>% mutate(State=str_trim(State,"right"))
race_data_2016<-race_data_2016%>%mutate_at(2:8,function(x)as.numeric(gsub(",","",x)))
fulldat <- election16 %>% left_join(race_data_2016, by=c("State"="Geography"))
glimpse(fulldat)
```
For the joining, I chose left join so that only data from matching states from 'RaceData2016' would be added to the 'election16' dataset. This is because I only wanted the data from the 50 U.S. states, and the RaceData16 dataset also contained data from the District of Columbia as its own 'state' variable, thus a left join would ensure that only the matching 50 states would be retained in the joined dataset since 'election16' had no equivalent D.C. row. A possible problem in analyzing this new dataset is that D.C. had a very high proportion of minority citizens, which may have been useful for examining correlations, however, for continuity, I thought it best to stick with the 50 states. 
```{R}
wider <- fulldat %>% pivot_wider(names_from="TrumpWin", values_from="Total")
glimpse(wider)
longer <- wider %>% pivot_longer(c("1","0"), names_to="TrumpWin", values_to="Total")
glimpse(longer)
longer <- longer%>%na.omit()
```
The data was already tidy, so I pivoted a column wider to prove that the information does not make as much sense presented in this way and that its current, tidy version is most readable. After making it wider, it split the TrumpWin into two columns, one for winning (1) and one for losing (0). This makes it more difficult to read since there are so many resulting N/A values. I then pivoted it back longer, which caused the 'Total' column to double up with N/A values, so I removed the N/As with na.omit() in order to return the dataset to its tidy, original setup. 

```{R}
fulldat <- fulldat %>% select(-c("X","Abr"))
fulldat <- fulldat %>% mutate(PercentWhite=(White/Total)*100)

majoritywhite <- fulldat %>% select(c("State", "Dem.Rep", "TrumpWin", "PercentWhite")) %>% group_by(State) %>% filter(PercentWhite>=50) %>% arrange(desc(PercentWhite))
majoritywhite
```

```{R}
fulldat %>% filter(Dem.Rep>0) %>% summarize(mean(Income))
fulldat %>% filter(Dem.Rep<0) %>% summarize(mean(Income))
59760.72-51453.43
```

```{R}
#install.packages("ggpubr")
#library("ggpubr")
percentwhitelose <- fulldat %>% group_by(TrumpWin) %>% filter(TrumpWin==0) %>% arrange(desc(PercentWhite)) %>% select(c("State", "TrumpWin", "PercentWhite"))

fivenum(percentwhitelose$PercentWhite)

percentwhitewin <- fulldat %>% group_by(TrumpWin) %>% filter(TrumpWin==1) %>% arrange(desc(PercentWhite)) %>% select(c("State", "TrumpWin", "PercentWhite"))

fivenum(percentwhitewin$PercentWhite)

```

```{R}
fulldat <- fulldat %>% mutate("Party" = ifelse(Dem.Rep > 0, "Dem", "Rep")) 
glimpse(fulldat)
Party <- as.factor(fulldat$Party)
fulldat %>% group_by(Party) %>% summarize(mean(HS)) 
```
```{R}
min(fulldat$BA)
max(fulldat$BA)
median(fulldat$BA)
quantile(fulldat$BA)

first <- fulldat %>% group_by(State) %>% filter(BA>=19.2&BA<25.95)
second <- fulldat %>% group_by(State) %>% filter(BA>=25.95&BA<28.2)
third <- fulldat %>% group_by(State) %>% filter(BA>=28.2&BA<31.775)
fourth <- fulldat %>% group_by(State) %>% filter(BA>=31.775&BA<=40.5)

mean(first$Dem.Rep)
mean(second$Dem.Rep)
mean(third$Dem.Rep)
mean(fourth$Dem.Rep)
```


```{R}
fulldat %>% group_by(Party) %>% summarize(mean(Black.or.African.American)) 
```
```{R}
fulldat %>% filter(TrumpWin==1) %>% summarize(mean(Black.or.African.American))
fulldat %>% filter(TrumpWin==0) %>% summarize(mean(Black.or.African.American))
```
  I began by mutating the dataset 'fulldat' to add a column that broke down the race into 'PercentWhite' to make it easier to see states with a majority white population, of white every single state had one to varying degrees. I mainly did this also to find correlations between the percent of white citizens in each state and the voting patterns of the state. I then began to examine the voting pattern differences in each state based on various factors. For example, I compared the average income per capita in states with Democratic leans and states with Republican leans and found the average difference was only about 8307.29, which I did not think would be enough to cause a major difference in voting patterns, but the higher per capita income was for Democratic states. I then broke down the PercentWhite by Trump Winning (1) or Trump Losing (0), and the five number summary showed that there wasn't a major difference in the summary statistics (aside from the outlier of Hawaii). Since I did not see much difference between PercentWhite, I examined the mean HS education by state for each party, and they were almost exactly the same. 
  I moved onto quartiles to divide the percent of individuals with college degrees in each state. It was interesting to find that the Democratic lean increased from the bottom to the top quartile, indicating that states with more college graduates voted Democrat. There were also, on average, many more African American individuals in States that were Democratic leaning. I also compared the difference in African American populations between states where Trump won and states where he didn't. There was ~10000 person difference between the two, which is not a major difference and could likely only be due to differing sized states and less with voting patterns. 



```{R fig.width=9, fig.height=9}
isnum <-fulldat%>%select_if(is.numeric)
head(isnum)
#numericdata <- isnum%>%select(-c("TrumpWin"))
#head(numericdata)
glimpse(cor(isnum))
tidycor<-cor(isnum)%>%as.data.frame%>%
rownames_to_column%>%
pivot_longer(-1,names_to="name",values_to="correlation")
head(tidycor)

tidycor%>%ggplot(aes(rowname,name,fill=correlation))+
geom_tile()+
scale_fill_gradient2(low="red",mid="white",high="blue")+
geom_text(aes(label=round(correlation,2)),color = "black", size = 2)+
theme(axis.text.x = element_text(angle = 45, hjust = 1))+
coord_fixed()+ggtitle("Correlation Heat Map of 2016 Presidential Election Data")+xlab("")+ylab("")

```
While many of the correlations were insignificant since there were so many race variables, a few stuck out as interesting. There was a strong positive correlation between the Advanced degrees variable and Dem.Rep, meaning those states with higher percentages of advanced degree-holders were democratic. There was also a strong negative correlation with TrumpWin and advanced degree holders, and the same correlation was found between TrumpWin and bachelors degree holders. Interestingly, there was a negative correlation between TrumpWin and Income variables. Mainly, the most significant correlations were between education levels and party leans.


```{R}
fulldat<-fulldat%>%mutate(Party=factor(Party,levels=c("Rep","Dem"),labels=c("Rep","Dem")))
ggplot(fulldat, aes(x = TrumpWin, y = Adv, fill=Party))+
geom_bar(position="dodge", stat="summary",fun.y="mean")+scale_fill_brewer(palette = "Set1")+scale_x_continuous(breaks=seq(0, 1))+scale_y_continuous(breaks=seq(0, 20, 2))+
geom_errorbar(position = position_dodge(1), stat="summary", fun.data="mean_se", width=.1)+ggtitle("Election Results by Percent of Advanced Degree Holders and Party") + ylab("Percent of Advanced Degree Holders") + xlab("Trump Won (1) or Lost (0)")

```
The above bar plot counts the percentage of advanced degree holders in states where Trump won or lost, grouped by party lean. Based on the bar chart above, there were more advanced degree holders in states that did not vote for Trump compared to states that did vote for Trump. Not only this, but it shows that more advanced degree holders come from states that have a democratic lean as well. 


```{R}
fulldat<-fulldat%>%mutate(Party=factor(Party,levels=c("Rep","Dem"),labels=c("Rep","Dem")))
ggplot(fulldat, aes(Income, BA, color=Party))+geom_point(size = 2)+scale_color_brewer(palette = "Set1")+ggtitle("State Party Lean by Bachelors Degree Holders and Per Capita Income") + ylab("Percentage of Bachelors Degree Holders (%)") + xlab("Income Per Capita ($)")

```
This scatter plot shows the spread of the average income per capita by the percentage of bachelors degree holders grouped by party. From the plot, it is easy to see that the democratic leaning states tend to have a higher average income per capita, as well as a higher percentage of bachelors degree holders. This is consistent with most of the earlier findings in this project that education seems to be the biggest factor in voting patterns. 

```{R}
library(cluster)

pam_dat <-fulldat %>% select(-State)
sil_width<-vector()
for(i in 2:10){
  pam_fit <- pam(pam_dat, k = i)
  sil_width[i] <- pam_fit$silinfo$avg.width
}

ggplot()+geom_line(aes(x=1:10,y=sil_width))+scale_x_continuous(name="k",breaks=1:10)
sil_width[2]
#result is 2 clusters
pam1<-pam_dat %>% select(-1) %>% pam(2)
pam1 
pamclust<-fulldat %>% mutate(cluster=as.factor(pam1$clustering))

pamclust %>% ggplot(aes(Dem.Rep,BA,color=cluster))+geom_point()

pam2<-fulldat%>%select(c(Dem.Rep,HS,BA,Adv))%>%pam(2)
pam2
final<-fulldat%>%mutate(cluster=as.factor(pam2$clustering))

ggplot(final, aes(x=HS,y=Dem.Rep, color=cluster))+geom_point()

library(GGally)
fulldat%>%select(c(Dem.Rep,HS,BA,Adv))%>%mutate(cluster=as.factor(pam2$clustering))%>%
  ggpairs(columns=1:4,aes(color=cluster))

```
The data was first processed to include only numeric variables, and this data was plugged into a ggplot to generate the average silhouette width, of which 2 clusters gave the largest. Thus, 2 clusters were chosen, and the graph was generated to cluster the four variables Dem.Rep, HS, BA, and Adv, visualized by Dem.Rep and BA. I generated two plots, and the second cluster plot that I generated gave a more distinct difference between clusters, as it showed a clear cutoff in grouping with higher education. However, to more clearly show the correlations, a plot to generate all pairwise correlations was generated. These much more clearly showed the strong positive correlations between both advanced degree holders and bachelors degree holders with larger democratic leans. BA (bachelors) had a slighly less strong correlation than did Adv (advanced degrees). High school education had a very small negative correlation, so it seems to be the education level that determines voting patterns the least, which was also indicated in one of the first summary statistics aforementioned in this project. Overall, the well-clustered plots generated in this pair plot indicates that these varying education levels seem to be the most strongly correlated with voting patterns in the 2016 election.

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
